/*
 * Builds `styles.css` from `src/styles.src.css` plus one block of rules per
 * indentation level.
 *
 * Obsidian loads `styles.css` for us and plugins may not attach their own
 * <style> elements, so every selector has to be known ahead of time. Only the
 * values change at runtime: `main.ts` writes a custom property per level onto
 * the body of each open window, and the rules below read it. A level the user
 * has not configured leaves its property unset and falls back to Obsidian's
 * own marker.
 *
 * Indentation levels are counted as the number of LIs in the parent chain,
 * regardless of whether they sit in an OL or a UL, which is what the Edit Mode
 * view plugin does too.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { maxLevel } = JSON.parse(readFileSync(join(root, "src/config.json"), "utf8"));

/** `.markdown-rendered li li … <rest>` for the given level. */
const sel = (level, rest) => [".markdown-rendered", ...Array(level).fill("li"), rest].join(" ");

const out = [readFileSync(join(root, "src/styles.src.css"), "utf8").trimEnd(), ""];

out.push(`/* Everything below is generated by scripts/build-styles.mjs. */`, "");

for (let level = 0; level < maxLevel; level++) {
	out.push(
		`${sel(level, "ol > li::marker")} { content: var(--lawlist-ol-${level}, normal); }`,
		`${sel(level, "ul.has-list-bullet > li::marker")} { content: var(--lawlist-ul-${level}, ""); color: var(--list-marker-color); }`,
		`${sel(level, "ul > li > .list-bullet::after")} { visibility: var(--lawlist-ul-bullet-${level}, visible); }`,
		""
	);
}

// Levels deeper than maxLevel would otherwise inherit the styling of level
// maxLevel - 1, because a shorter selector still matches them. These rules are
// more specific than any of the above, so they stop the styling there.
out.push(
	"/* Beyond the last configurable level, hand markers back to Obsidian. */",
	`${sel(maxLevel, "ol > li::marker")} { content: normal; }`,
	`${sel(maxLevel, "ul.has-list-bullet > li::marker")} { content: ""; }`,
	`${sel(maxLevel, "ul > li > .list-bullet::after")} { visibility: visible; }`,
	""
);

writeFileSync(join(root, "styles.css"), out.join("\n"));
console.log(`styles.css: ${maxLevel} levels`);
